# 配置dev环境
spring:
  profiles: dev
  application:
    name: msc-eureka-server-config
server:
  port: 8400
eureka:
  instance:
    # 指定eureka主机
    hostname: eureka8400.com
  client:
    # 指定是否向注册中心注册自己
    register-with-eureka: false
    # 指定此客户端是否能够获取eureka注册信息
    fetch-registry: false
    # 暴露服务中心地址
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka

---
# 配置test环境
spring:
  profiles: test
  application:
    name: msc-eureka-server-config
server:
  port: 8500
eureka:
  instance:
    # 指定eureka主机
    hostname: eureka8500.com
  client:
    # 指定是否向注册中心注册自己
    register-with-eureka: false
    # 指定此客户端是否能够获取eureka注册信息
    fetch-registry: false
    # 暴露服务中心地址
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka
